spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=shop_backend_test
    username: sa
    password: 1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true