#spring.application.name=ecommerce
#
#spring.profiles.active=dev
#
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=shop_backend_dev;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=1
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#
#
#logging.level.org.springframework.web=DEBUG
#

spring.profiles.active=dev